# Generated by Django 3.2.13 on 2023-10-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='request_number',
            field=models.CharField(default='cgyVm3l354', max_length=10, unique=True),
        ),
    ]
