# Generated by Django 4.2.5 on 2023-10-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='request_number',
            field=models.CharField(default='UUe2UDJVy3', max_length=10, unique=True),
        ),
    ]
