# Generated by Django 4.2.5 on 2023-10-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_appointment_request_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='request_number',
            field=models.CharField(default='gUL6tK7Zbg', max_length=10, unique=True),
        ),
    ]
