# Generated by Django 4.2.5 on 2023-10-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_alter_appointment_request_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='request_number',
            field=models.CharField(default='aL7W7LzX4a', max_length=10, unique=True),
        ),
    ]
