# Generated by Django 3.2.13 on 2023-10-01 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authitacation', '0003_auto_20231001_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='city',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='province',
        ),
    ]
