# Generated by Django 3.2.13 on 2023-10-04 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authitacation', '0004_auto_20231001_2341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patient',
        ),
    ]
