# Generated by Django 3.2.13 on 2023-09-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('symptoms', models.TextField()),
                ('spot_number', models.CharField(max_length=10)),
                ('estimated_time', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
