<<<<<<< HEAD
# Generated by Django 4.2.5 on 2023-11-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfqueue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientQueueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('symptoms', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('estimated_time', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('closing_time', models.DateTimeField()),
                ('spot_number', models.IntegerField()),
            ],
        ),
    ]
=======
# Generated by Django 4.2.7 on 2023-11-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfqueue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientQueueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('symptoms', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('estimated_time', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('closing_time', models.DateTimeField()),
                ('spot_number', models.IntegerField()),
            ],
        ),
    ]
>>>>>>> 0951900e3a71d5d3e4065bc79e6ef0236754c378
