# Generated by Django 3.2.13 on 2023-10-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfqueue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=15, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('symptoms', models.TextField()),
                ('estimated_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Awaiting Consultation', 'Awaiting Consultation'), ('In Consultation', 'In Consultation'), ('Done with Consultation', 'Done with Consultation')], default='Awaiting Consultation', max_length=50)),
                ('closing_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
