# Generated by Django 3.2.13 on 2023-10-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfqueue', '0003_patientqueue_spot_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientqueue',
            name='symptoms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
