# Generated by Django 3.2.13 on 2023-10-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfqueue', '0004_alter_patientqueue_symptoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='patientqueue',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='patientqueue',
            name='symptoms',
            field=models.ManyToManyField(blank=True, to='selfqueue.Symptom'),
        ),
    ]
