# Generated by Django 3.2.13 on 2023-10-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfqueue', '0007_patientqueue_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientqueue',
            name='symptoms',
            field=models.ManyToManyField(blank=True, to='selfqueue.Symptom'),
        ),
    ]
