# Generated by Django 4.2.5 on 2023-11-05 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0017_appointment_is_confirmed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('selfqueue', '0008_patientqueue_symptoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('prescription', models.TextField()),
                ('service', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('referrals', models.TextField(blank=True)),
                ('further_examination', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfqueue.patientqueue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_question', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('rating', models.PositiveIntegerField()),
                ('message', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.doctor')),
            ],
        ),
    ]
