# Generated by Django 4.2.7 on 2023-11-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfqueue', '0009_medicalrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctor_code',
        ),
    ]
