# Generated by Django 4.2.5 on 2023-10-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLocation',
            new_name='ambulanceRequest',
        ),
    ]
