# Generated by Django 4.2.5 on 2023-10-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0003_ambulancerequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancerequest',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ambulancerequest',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
