# Generated by Django 4.2.5 on 2023-10-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0004_alter_ambulancerequest_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancerequest',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
